<a href="https://colab.research.google.com/github/jjanuario/AprendendoMachineLearn/blob/master/pytorch_mario_filho_live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# São Paulo 04 de Maio de 2020
## Live 24 Tutorial Basico de Pytorch
### Uma biblioteca de Deep Learn do Facebook
jeferson@asterixsolucoes.com.br

In [0]:
# Instalando as dependencia
!pip install --upgrade pip
#!pip install pytorch

Requirement already up-to-date: pip in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (20.1)


In [0]:
# Realizando os imports
import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np

In [0]:
t = torch.Tensor([1,2,3])
t

tensor([1., 2., 3.])

In [0]:
array = np.array([1,2,3])
t2 = torch.from_numpy(array)

In [0]:
t2

tensor([1, 2, 3])

In [0]:
t *10

tensor([10., 20., 30.])

In [0]:
t.dot(t)

tensor(14.)

In [0]:
t3 = torch.Tensor([2,2,2])
t3.dot(t3)

tensor(12.)

In [0]:
!ls sample_data/california_housing_test.csv

sample_data/california_housing_test.csv


In [0]:
# Lendo o dataset
data_test = pd.read_csv("sample_data/california_housing_test.csv")
data_train = pd.read_csv("sample_data/california_housing_train.csv")
data_train.sample(3)

longitude  latitude  ...  median_income  median_house_value
7955     -118.41     34.16  ...         6.3703            465800.0
11442    -121.24     38.72  ...         4.9000            203700.0
6307     -118.25     33.95  ...         0.9751             95500.0

[3 rows x 9 columns]