<a href="https://colab.research.google.com/github/jjanuario/AprendendoMachineLearn/blob/master/notebooks/pytorch_mario_filho_live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# São Paulo 04 de Maio de 2020
## Live 24 Tutorial Basico de Pytorch
### Uma biblioteca de Deep Learn do Facebook
jeferson@asterixsolucoes.com.br

In [1]:
# Instalando as dependencia
!pip install --upgrade pip
#!pip install pytorch

     |████████████████████████████████| 1.5MB 2.8MB/s 
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1


In [0]:
# Realizando os imports
import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np

In [3]:
t = torch.Tensor([1,2,3])
t

tensor([1., 2., 3.])

In [0]:
array = np.array([1,2,3])
t2 = torch.from_numpy(array)

In [5]:
t2

tensor([1, 2, 3])

In [6]:
t *10

tensor([10., 20., 30.])

In [7]:
t.dot(t)

tensor(14.)

In [8]:
t3 = torch.Tensor([2,2,2])
t3.dot(t3)

tensor(12.)

In [9]:
!ls sample_data/california_housing_test.csv

sample_data/california_housing_test.csv


In [14]:
# Lendo o dataset
data_test = pd.read_csv("sample_data/california_housing_test.csv")
data_train = pd.read_csv("sample_data/california_housing_train.csv")
data_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [0]:
# Aqui tem um comentario
X = data_train.drop('median_house_value', axis=1)
y = data_train['median_house_value']

In [0]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
# Minhas features são 8 enviando para 100 neoronios
    self.fc1 = nn.Linear(8, 100)
    self.fc2 = nn.Linear(100, 100)
# Aqui temos cem neoronios entregando para um neoronio tomador de descissoes
    self.out = nn.Linear(100, 1)

  def forward(self, x):
    x = F.normalize(x)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    
    y = self.out(x)

    return y


In [34]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=8, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=100, bias=True)
  (out): Linear(in_features=100, out_features=1, bias=True)
)


In [0]:
X_tensor = torch.from_numpy(data_train.values[:, :-1]).float()
y_tensor = torch.from_numpy(data_train.values[:, -1]).float()

y_tensor = torch.log(y_tensor)

In [43]:
# Verificando pesos de optimização da nossa rede neural
print(list(net.parameters()))

[Parameter containing:
tensor([[ 0.0125, -0.1031,  0.0435, -0.1617, -0.1109,  0.3219,  0.3617,  0.1351],
        [ 0.0774, -0.1654,  0.1126, -0.1666, -0.1305,  0.2637, -0.0133,  0.1857],
        [ 0.2762, -0.2532, -0.1198, -0.0275, -0.3093, -0.1702,  0.0816, -0.2284],
        [-0.0730,  0.2001,  0.3153,  0.1061, -0.2203,  0.1430,  0.0549, -0.0488],
        [-0.1805, -0.2388,  0.1842,  0.0368, -0.0817,  0.0484, -0.2353,  0.2307],
        [-0.2937,  0.2470,  0.2023,  0.3271,  0.0171,  0.1375, -0.3019, -0.1981],
        [-0.0772, -0.0335,  0.1342, -0.2881,  0.2510, -0.1281, -0.2286,  0.0663],
        [-0.1824, -0.2328, -0.1682,  0.2146,  0.0221, -0.1651, -0.1996,  0.3227],
        [ 0.2942, -0.2002, -0.0345,  0.2626,  0.0847,  0.1448,  0.0572,  0.2334],
        [ 0.0876,  0.2889, -0.2323,  0.2480, -0.1574, -0.0370, -0.0058, -0.1684],
        [-0.1571, -0.2014,  0.1969,  0.1231,  0.1040,  0.0574, -0.1044, -0.3298],
        [ 0.0437,  0.2498, -0.0446,  0.0223, -0.0519,  0.1066,  0.2883,  0.

In [0]:
import torch.optim as optim
optimizer = optim.Adam(net.parameters(), lr=0.0001)

In [0]:
# Indicação de errro
criterion = nn.MSELoss()

In [54]:
for i in range(999):
  optimizer.zero_grad()
  prediction = net(X_tensor)
  loss = criterion(prediction, y_tensor)
  loss.backward()
  optimizer.step()

  prediction2 = torch.exp(net(X_tensor))
  loss = criterion(prediction2, torch.exp(y_tensor))
  print("Monitor de loss:", torch.sqrt(loss))

Monitor de loss: tensor(118800.2422, grad_fn=<SqrtBackward>)
Monitor de loss: tensor(118800.2422, grad_fn=<SqrtBackward>)


KeyboardInterrupt: ignored