# São Paulo 04 de Maio de 2020
## Live 24 Tutorial Basico de Pytorch
### Uma biblioteca de Deep Learn do Facebook
jeferson@asterixsolucoes.com.br

In [3]:
# Instalando as dependencia
!pip install --upgrade pip
#!pip install pytorch

Requirement already up-to-date: pip in /home/nbuser/anaconda3_501/lib/python3.6/site-packages (20.1)


In [10]:
# Realizando os imports
import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd
import numpy as np

In [7]:
t = torch.Tensor([1,2,3])
t

tensor([1., 2., 3.])

In [12]:
array = np.array([1,2,3])
t2 = torch.from_numpy(array)

In [13]:
t2

tensor([1, 2, 3])

In [14]:
t *10

tensor([10., 20., 30.])

In [15]:
t.dot(t)

tensor(14.)

In [19]:
t3 = torch.Tensor([2,2,2])
t3.dot(t3)

tensor(12.)

In [20]:
# Lendo o dataset
data = pd.read_csv("../data/housing.csv")
data.sample(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16799    -122.44     37.67                35.0       1814.0           365.0   
14110    -117.12     32.75                13.0       2795.0           773.0   
6930     -118.08     34.02                14.0       3789.0           810.0   

       population  households  median_income  median_house_value  \
16799      1025.0       384.0         4.4250            268400.0   
14110      1869.0       690.0         2.1767            101800.0   
6930       2551.0       793.0         2.9321            144200.0   

      ocean_proximity  
16799      NEAR OCEAN  
14110      NEAR OCEAN  
6930        <1H OCEAN